---
# tasks file for httpd_website
    - name: Install apache httpd
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes
    - name: Copy File with owner and permissions
      ansible.builtin.copy:
        src: files/Responsive-static-website-using-html-css-bootstrap/
        dest: /var/www/html
        owner: root
        group: root
        mode: "0644"
